### ISSUE TITLE
Hyperlinks in the Dialog

### ISSUE THREAD

**Issue by vrcrush** [abnerfcastro/watson-chatbot-boilerplate#3]
![hyperlink](https://user-images.githubusercontent.com/35403901/44595679-65824c00-a78f-11e8-8235-87cf2bcb810c.png)

hi, my dialog contains hyperlinks, but when it renders in the chatbot window it shows the HTML code.
any suggestions to fix this? thank you!

**Comment by abnerfcastro** [comment]
Hi @vrcrush ,

My suggestion is to use the [ngBingHtml ](https://docs.angularjs.org/api/ng/directive/ngBindHtml) Angular directive. It's currently only binding the text message content (see on `public/views/home.view.html` [file](https://github.com/abnerfcastro/watson-chatbot-boilerplate/blob/f2a4aa4147a3c9bc922fbbf47fe8e5db2c340f13/public/views/home.view.html#L41)). I think this directive will render the message in HTML.

**Comment by vrcrush** [comment]
Thank you Abner.
I am reading about the bingHTML Angular directive. Do you think this is easy enough task for somebody that has zero Angular experience?

any good resource to read about it?

your chatbot code solves the problem I had with mine (the scrolling), but i am having issues with the html code render.

thanks!

Pablo


________________________________
De: Abner Castro <notifications@github.com>
Enviado: viernes, 24 de agosto de 2018 11:46 a. m.
Para: abnerfcastro/watson-chatbot-boilerplate
CC: vrcrush; Mention
Asunto: Re: [abnerfcastro/watson-chatbot-boilerplate] Hyperlinks in the Dialog (#3)


Hi @vrcrush<https://github.com/vrcrush> ,

My suggestion is to use the ngBingHtml <https://docs.angularjs.org/api/ng/directive/ngBindHtml> Angular directive. It's currently only binding the text message content (see on public/views/home.view.html file). I think this directive will render the message in HTML.

**Comment by abnerfcastro** [comment]
@vrcrush ,

I've never used it myself, but I just did a quick research and it's actually quite easy to implement. As it is very unsafe to allow HTML injection in your code, Angular JS provides a module called `ngSanitize` (you can read more about it [here](https://stackoverflow.com/questions/33209938/what-is-the-purpose-of-angular-sanitize)). To use this module, you need to first include it in the `public/index.html` [file](https://github.com/abnerfcastro/watson-chatbot-boilerplate/blob/f2a4aa4147a3c9bc922fbbf47fe8e5db2c340f13/public/index.html#L62). You might want to add the following snippet below [this line](https://github.com/abnerfcastro/watson-chatbot-boilerplate/blob/f2a4aa4147a3c9bc922fbbf47fe8e5db2c340f13/public/index.html#L61):

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.5/angular-sanitize.min.js"></script>
```

After including it, you will have to add `ngSanitize` to the list of modules your Angular application depends on. You can that on `public/js/app.js` [file](https://github.com/abnerfcastro/watson-chatbot-boilerplate/blob/master/public/js/app.js):

```js
    angular.module('chatbot.app', [
        'ngRoute',
        'chatbot.app.services',
        'luegg.directives',
        'ngSanitize'
    ]);
```

Now you can safely use `ngBindHtml`. To do that, change [this](https://github.com/abnerfcastro/watson-chatbot-boilerplate/blob/f2a4aa4147a3c9bc922fbbf47fe8e5db2c340f13/public/views/home.view.html#L40) `p` tag to 

```html
<div ng-bind-html="message.content"></div>
```

You can learn more on these links:
[How to use ng-bing-html?](https://stackoverflow.com/questions/27464446/how-to-use-ng-bind-html)
[How To Use NG-Bind-html in Angular JS?](https://www.youtube.com/watch?v=eYa7E7iW8-8) (YouTube video)

I hope that helps.

Regards,

Abner

**Comment by vrcrush** [comment]
thank you so much!

that made the trick!


________________________________
De: Abner Castro <notifications@github.com>
Enviado: viernes, 24 de agosto de 2018 07:39 p. m.
Para: abnerfcastro/watson-chatbot-boilerplate
CC: vrcrush; Mention
Asunto: Re: [abnerfcastro/watson-chatbot-boilerplate] Hyperlinks in the Dialog (#3)


@vrcrush<https://github.com/vrcrush> ,

I've never used it myself, but I just did a quick research and it's actually quite easy to implement. As it is quite unsafe to allow HTML injection in your code, Angular JS provides a module called ngSanitize (you can read more about it here<https://stackoverflow.com/questions/33209938/what-is-the-purpose-of-angular-sanitize>). To use this module, you need to first include it in the public/index.html file<https://github.com/abnerfcastro/watson-chatbot-boilerplate/blob/f2a4aa4147a3c9bc922fbbf47fe8e5db2c340f13/public/index.html#L62>. You might want to add the following snipped below this line<https://github.com/abnerfcastro/watson-chatbot-boilerplate/blob/f2a4aa4147a3c9bc922fbbf47fe8e5db2c340f13/public/index.html#L61>:

<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.5/angular-sanitize.min.js"></script>

After including it, you will have to add ngSanitize to the list of modules your Angular application depends on. You can that on public/js/app.js file<https://github.com/abnerfcastro/watson-chatbot-boilerplate/blob/master/public/js/app.js>:

    angular.module('chatbot.app', [
        'ngRoute',
        'chatbot.app.services',
        'luegg.directives',
        'ngSanitize'
    ]);

Now you can safely use ngBindHtml. To do that, change this<https://github.com/abnerfcastro/watson-chatbot-boilerplate/blob/f2a4aa4147a3c9bc922fbbf47fe8e5db2c340f13/public/views/home.view.html#L40> p tag to

<div ng-bind-html="message.content"></div>

You can learn more on these links:
How to use ng-bing-html?<https://stackoverflow.com/questions/27464446/how-to-use-ng-bind-html>
How To Use NG-Bind-html in Angular JS?<https://www.youtube.com/watch?v=eYa7E7iW8-8> (YouTube video)

I hope that helps.

Regards,

Abner

**Comment by abnerfcastro** [comment]
Glad a I could help 👍
